#!/usr/bin/env python
import json
import sys

bumpx = int(sys.argv[1])
bumpy = int(sys.argv[2])

file = open('resources/standard.json', 'r')
coords = json.load(file)
file.close()

for coord in coords.values():
  coord[0] += bumpx
  coord[1] += bumpy

file = open('resources/standard.json', 'w')
json.dump(coords, file)
file.close()
