gameboard = {
  'nao': {'type': 'water', 'borders': ['nwg', 'cly', 'lvp', 'iri', 'mao']},
  'nwg': {'type': 'water', 'borders': ['bar', 'nwy', 'nth', 'edi', 'cly' 'nao']},
  'bar': {'type': 'water', 'borders': ['stp', 'nwy', 'nwg']},
  'stp': {'type': 'coastal', 'supply': 'russia', 'borders': ['bar', 'mos', 'lvn', 'bot', 'fin', 'nwy']},
  'mos': {'type': 'land', 'supply': 'russia', 'borders': ['stp', 'sev', 'ukr', 'war', 'lvn']},
  'sev': {'type': 'coastal', 'supply': 'russia', 'borders': ['mos', 'arm', 'bla', 'rum', 'ukr']},
  'arm': {'type': 'coastal', 'supply': 'none', 'borders': ['sev', 'syr', 'smy', 'ank', 'bla']},
  'syr': {'type': 'coastal', 'supply': 'none', 'borders': ['arm', 'eas', 'smy']},
  'eas': {'type': 'water', 'borders': ['smy', 'syr', 'ion', 'aeg']},
  'ion': {'type': 'water', 'borders': ['adr', 'alb', 'gre', 'aeg', 'eas', 'tun', 'tys', 'nap', 'apu']},
  'tun': {'type': 'coastal', 'supply': 'neutral', 'borders': ['tys', 'ion', 'naf', 'wes']},
  'naf': {'type': 'coastal', 'supply': 'none', 'borders': ['wes', 'tun', 'mao']},
  'mao': {'type': 'water', 'borders': ['nao', 'iri', 'eng', 'bre', 'gas', 'spa', 'por']},
  'iri': {'type': 'water', 'borders': ['nao', 'lvp', 'wal', 'eng', 'mao']},
}
